name: Publish package to GitHub Packages
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          distribution: 'openjdk'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: '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'
